version: '3.7'

services:
  db:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: observability
        POSTGRES_USER: alex
        POSTGRES_PASSWORD: pass